name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js 16
        run: |
          # Instala o Node.js 16
          curl -sL https://deb.nodesource.com/setup_16.x | bash -s
          apt-get install -y nodejs
          # Verifique a versão do Node.js para confirmar a instalação
          node -v

      - name: Instalar npm globalmente
        run: |
          # Instala o npm globalmente
          npm install -g npm

      - name: Instalar Atlas CLI
        run: |
          # Instala o Atlas CLI globalmente
          npm install -g atlas

      - name: Executar Validação HCL
        run: |
          # Substitua "atlasgo/rules/atlas.hcl" pelo caminho do seu arquivo HCL.
          npx atlas validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
