name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js 16 (com sudo)
        run: |
          # Execute 'apt-get update' with sudo (use with caution)
          sudo apt-get update
          # Install Node.js 16
          curl -sL https://deb.nodesource.com/setup_16.x | bash -s
          apt-get install -y nodejs
          # Verify Node.js version
          node -v

      - name: Instalar npm globalmente
        run: |
          # Install npm globally
          npm install -g npm

      - name: Instalar Atlas CLI
        run: |
          # Install Atlas CLI globally
          npm install -g atlas

      - name: Executar Validação HCL
        run: |
          # Substitute "atlasgo/rules/atlas.hcl" with your HCL file path.
          npx atlas validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
