name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Executar Validação HCL
        run: |
          # Substitua "atlasgo/rules/atlas.hcl" pelo caminho do seu arquivo HCL.
          # Substitua "./script.sql" pelo caminho do seu script SQL.
          npx atlas validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
