name: Deploy schema changes
run-name: I'm using Atlas 🚀
on: [push]
jobs:
  use-atlas:
    runs-on: [elastic-runner-dev]
    steps:
      - uses: ariga/setup-atlas@master
      - run: atlas version
      # - run: atlas schema apply ... 
