name: Setup Atlas
run-name: I'm using Atlas 
on: [push]
jobs:
  use-atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: atlas version

      # Add the HCL validation step here:
      - name: Run HCL validation
        run: |
          cd atlasgo/rules  # Navigate to the directory containing atlas.hcl
          atlas validate --dir sql  # Execute Atlasgo HCL validation, specifying the SQL scripts folder
    
