name: Setup Atlas
run-name: I'm using Atlas
on: [push]
jobs:
  use-atlas:
    runs-on: ubuntu-latest  # Assuming you're using Ubuntu-based runner
    steps:
      - uses: actions/checkout@v4
      - name: Check Atlas CLI installation
        run: |
          # Assuming Atlasgo is installed in /home/user/.local/bin (adjust if needed)
          /home/user/.local/bin/atlas --version
          if [ $? -eq 0 ]; then
            echo "Atlas CLI is installed."
          else
            echo "Atlas CLI is not installed or not in PATH."
            exit 1  # Exit with non-zero code to signal missing CLI
          fi
      - uses: ./  # Assuming your main script is here (optional)
      - run: /home/user/.local/bin/atlas version  # Specify the installation path (optional)

      # Add the HCL validation step here (assuming CLI is installed):
      - name: Run HCL validation (if installed)
        run: |
          cd atlasgo/rules  # Navigate to the directory containing atlas.hcl
          atlas validate --dir sql  # Execute Atlasgo HCL validation, specifying the SQL scripts folder
        # Check the exit code to indicate success or failure (optional)
        # if [ $? -eq 0 ]; then
        #   echo "HCL validation successful"
        # else
        #   echo "HCL validation failed!"
        #   exit 1  # Exit with non-zero code to signal failure
        # fi
