name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Baixar Atlas CLI Binário
        run: |
          # Baixar o binário do Atlas CLI para a versão 2.2.1
          curl -sL https://atlassian.github.io/atlas-cli/downloads/atlas-cli-2.2.1-linux-x64.tar.gz -o atlas-cli.tar.gz

          # Extrair o binário
          tar -xf atlas-cli.tar.gz

      - name: Executar Validação HCL
        run: |
          # Substitua "atlasgo/rules/atlas.hcl" pelo caminho do seu arquivo HCL.
          # Substitua "/path/to/extracted/atlas-cli" pelo caminho real do binário extraído.
          /path/to/extracted/atlas-cli validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
