name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Atlas CLI com apt
        run: |
          # Atualizar a lista de pacotes
          sudo apt-get update

          # Instalar o Atlas CLI
          sudo apt-get install -y atlas-cli

      - name: Executar Validação HCL
        run: |
          # Substitua "atlasgo/rules/atlas.hcl" pelo caminho do seu arquivo HCL.
          atlas validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
