name: Validar Scripts SQL com HCL Local

on:
  push:
    branches: [ main ]

jobs:
  validar-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Executar Validação HCL
        run: |
          npx atlas validate -f atlasgo/rules/atlas.hcl \
              -s 'file://./sql/meu_primeiro_sql.sql' \
              -o ./validation_results.json
